services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # Passes host environment variables into the Docker build arguments
      args:
        - DATABASE_URL=${DATABASE_URL}
        - APP_URL=${APP_URL}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - NODE_ENV=${NODE_ENV:-production}
        - NEXT_PUBLIC_HUBSPOT_OBJECTS_API=${NEXT_PUBLIC_HUBSPOT_OBJECTS_API}
        - NEXT_LEPINE_APARTMENTS_URL=${NEXT_LEPINE_APARTMENTS_URL}
        - NEXT_PUBLIC_GOOGLE_REVIEWS_API_KEY=${NEXT_PUBLIC_GOOGLE_REVIEWS_API_KEY}
        - NEXT_PUBLIC_LINKEDIN_MARKETING_API_TOKEN=${NEXT_PUBLIC_LINKEDIN_MARKETING_API_TOKEN}
        - NEXT_PUBLIC_DAYFORCE_JOBS_URL=${NEXT_PUBLIC_DAYFORCE_JOBS_URL}
        - DAYFORCE_JOBS_API_URL=${DAYFORCE_JOBS_API_URL}
        - SOLUTIONEERS_SERVICES_SECRET=${SOLUTIONEERS_SERVICES_SECRET}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_LEASING_ACCESS_CODE=${NEXT_PUBLIC_LEASING_ACCESS_CODE}
        - NEXT_PUBLIC_HUBSPOT_CONNECTOR_KEY=${NEXT_PUBLIC_HUBSPOT_CONNECTOR_KEY}
        - NODEMAILER_USER=${NODEMAILER_USER}
        - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
        - NEXT_PUBLIC_YOUTUBE_API_KEY=${NEXT_PUBLIC_YOUTUBE_API_KEY}
        - NEXT_PUBLIC_YOUTUBE_CHANNEL_ID=${NEXT_PUBLIC_YOUTUBE_CHANNEL_ID}
        - NEXT_PUBLIC_INSTAGRAM_APP_ID=${NEXT_PUBLIC_INSTAGRAM_APP_ID}
        - NEXT_PUBLIC_INSTAGRAM_APP_SECRET=${NEXT_PUBLIC_INSTAGRAM_APP_SECRET}
        - NEXT_PUBLIC_HUBSPOT_CONTEST_API_KEY=${NEXT_PUBLIC_HUBSPOT_CONTEST_API_KEY}
        - NEXT_PUBLIC_LEPINE_APARTMENTS_URL=${NEXT_PUBLIC_LEPINE_APARTMENTS_URL}
        - NEXT_PUBLIC_FACEBOOK_POSTS_LONG_LIVED_PAGE_TOKEN=${NEXT_PUBLIC_FACEBOOK_POSTS_LONG_LIVED_PAGE_TOKEN}
        - NEXT_PUBLIC_LEPINE_MARKETING_DASHBOARD_AUTH=${NEXT_PUBLIC_LEPINE_MARKETING_DASHBOARD_AUTH}
        - NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID}
        - NEXT_PUBLIC_GOOGLE_ADS_CLIENT_SECRET=${NEXT_PUBLIC_GOOGLE_ADS_CLIENT_SECRET}
        - NEXT_PUBLIC_GOOGLE_ADS_DEVELOPER_TOKEN=${NEXT_PUBLIC_GOOGLE_ADS_DEVELOPER_TOKEN}
        - NEXT_PUBLIC_GOOGLE_ADS_REFRESH_TOKEN=${NEXT_PUBLIC_GOOGLE_ADS_REFRESH_TOKEN}
        - NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID=${NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID}
        - NEXT_PUBLIC_GOOGLE_ADS_LOGIN_CUSTOMER_ID=${NEXT_PUBLIC_GOOGLE_ADS_LOGIN_CUSTOMER_ID}
        - GREEN_BUTTON_ENCRYPTION_KEY=${GREEN_BUTTON_ENCRYPTION_KEY}
        - NEXT_PUBLIC_INSTAGRAM_APP_TOKEN=${NEXT_PUBLIC_INSTAGRAM_APP_TOKEN}
    image: lepine-frontend:latest
    container_name: lepine-frontend
    restart: unless-stopped
    # Supplies the environment variables to the running container
    env_file:
      - .env
    ports:
      - "8080:8080"