# 1. Use your original Node version
FROM node:22-slim

# Install OpenSSL 1.1.x if needed for older Node/Prisma versions
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# Copy package files first to leverage Docker layer caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# 2. DECLARE ALL BUILD ARGUMENTS
# DigitalOcean will pass values from your App Spec into these placeholders
ARG DATABASE_URL
ARG APP_URL
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG NODE_ENV
ARG NEXT_PUBLIC_HUBSPOT_OBJECTS_API
ARG NEXT_LEPINE_APARTMENTS_URL
ARG NEXT_PUBLIC_GOOGLE_REVIEWS_API_KEY
ARG NEXT_PUBLIC_LINKEDIN_MARKETING_API_TOKEN
ARG NEXT_PUBLIC_DAYFORCE_JOBS_URL
ARG DAYFORCE_JOBS_API_URL
ARG SOLUTIONEERS_SERVICES_SECRET
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_LEASING_ACCESS_CODE
ARG NEXT_PUBLIC_HUBSPOT_CONNECTOR_KEY
ARG NODEMAILER_USER
ARG NODEMAILER_PASSWORD
ARG NEXT_PUBLIC_YOUTUBE_API_KEY
ARG NEXT_PUBLIC_YOUTUBE_CHANNEL_ID
ARG NEXT_PUBLIC_INSTAGRAM_APP_ID
ARG NEXT_PUBLIC_INSTAGRAM_APP_SECRET
ARG NEXT_PUBLIC_HUBSPOT_CONTEST_API_KEY
ARG NEXT_PUBLIC_LEPINE_APARTMENTS_URL
ARG NEXT_PUBLIC_FACEBOOK_POSTS_LONG_LIVED_PAGE_TOKEN
ARG NEXT_PUBLIC_LEPINE_MARKETING_DASHBOARD_AUTH
ARG NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_ADS_CLIENT_SECRET
ARG NEXT_PUBLIC_GOOGLE_ADS_DEVELOPER_TOKEN
ARG NEXT_PUBLIC_GOOGLE_ADS_REFRESH_TOKEN
ARG NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID
ARG NEXT_PUBLIC_GOOGLE_ADS_LOGIN_CUSTOMER_ID
ARG GREEN_BUTTON_ENCRYPTION_KEY
ARG NEXT_PUBLIC_INSTAGRAM_APP_TOKEN

# 3. CONVERT ARGS TO ENVIRONMENT VARIABLES
# This makes them accessible to 'process.env' during 'npm run build'
ENV DATABASE_URL=$DATABASE_URL \
    APP_URL=$APP_URL \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_USERNAME=$DATABASE_USERNAME \
    DATABASE_PASSWORD=$DATABASE_PASSWORD \
    NODE_ENV=$NODE_ENV \
    NEXT_PUBLIC_HUBSPOT_OBJECTS_API=$NEXT_PUBLIC_HUBSPOT_OBJECTS_API \
    NEXT_LEPINE_APARTMENTS_URL=$NEXT_LEPINE_APARTMENTS_URL \
    NEXT_PUBLIC_GOOGLE_REVIEWS_API_KEY=$NEXT_PUBLIC_GOOGLE_REVIEWS_API_KEY \
    NEXT_PUBLIC_LINKEDIN_MARKETING_API_TOKEN=$NEXT_PUBLIC_LINKEDIN_MARKETING_API_TOKEN \
    NEXT_PUBLIC_DAYFORCE_JOBS_URL=$NEXT_PUBLIC_DAYFORCE_JOBS_URL \
    DAYFORCE_JOBS_API_URL=$DAYFORCE_JOBS_API_URL \
    SOLUTIONEERS_SERVICES_SECRET=$SOLUTIONEERS_SERVICES_SECRET \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY \
    NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID \
    NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL \
    NEXT_PUBLIC_LEASING_ACCESS_CODE=$NEXT_PUBLIC_LEASING_ACCESS_CODE \
    NEXT_PUBLIC_HUBSPOT_CONNECTOR_KEY=$NEXT_PUBLIC_HUBSPOT_CONNECTOR_KEY \
    NODEMAILER_USER=$NODEMAILER_USER \
    NODEMAILER_PASSWORD=$NODEMAILER_PASSWORD \
    NEXT_PUBLIC_YOUTUBE_API_KEY=$NEXT_PUBLIC_YOUTUBE_API_KEY \
    NEXT_PUBLIC_YOUTUBE_CHANNEL_ID=$NEXT_PUBLIC_YOUTUBE_CHANNEL_ID \
    NEXT_PUBLIC_INSTAGRAM_APP_ID=$NEXT_PUBLIC_INSTAGRAM_APP_ID \
    NEXT_PUBLIC_INSTAGRAM_APP_SECRET=$NEXT_PUBLIC_INSTAGRAM_APP_SECRET \
    NEXT_PUBLIC_HUBSPOT_CONTEST_API_KEY=$NEXT_PUBLIC_HUBSPOT_CONTEST_API_KEY \
    NEXT_PUBLIC_LEPINE_APARTMENTS_URL=$NEXT_PUBLIC_LEPINE_APARTMENTS_URL \
    NEXT_PUBLIC_FACEBOOK_POSTS_LONG_LIVED_PAGE_TOKEN=$NEXT_PUBLIC_FACEBOOK_POSTS_LONG_LIVED_PAGE_TOKEN \
    NEXT_PUBLIC_LEPINE_MARKETING_DASHBOARD_AUTH=$NEXT_PUBLIC_LEPINE_MARKETING_DASHBOARD_AUTH \
    NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID \
    NEXT_PUBLIC_GOOGLE_ADS_CLIENT_SECRET=$NEXT_PUBLIC_GOOGLE_ADS_CLIENT_SECRET \
    NEXT_PUBLIC_GOOGLE_ADS_DEVELOPER_TOKEN=$NEXT_PUBLIC_GOOGLE_ADS_DEVELOPER_TOKEN \
    NEXT_PUBLIC_GOOGLE_ADS_REFRESH_TOKEN=$NEXT_PUBLIC_GOOGLE_ADS_REFRESH_TOKEN \
    NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID=$NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID \
    NEXT_PUBLIC_GOOGLE_ADS_LOGIN_CUSTOMER_ID=$NEXT_PUBLIC_GOOGLE_ADS_LOGIN_CUSTOMER_ID \
    GREEN_BUTTON_ENCRYPTION_KEY=$GREEN_BUTTON_ENCRYPTION_KEY \
    NEXT_PUBLIC_INSTAGRAM_APP_TOKEN=$NEXT_PUBLIC_INSTAGRAM_APP_TOKEN

# 4. Build the Next.js app
# Now that ENV is set, 'getStaticPaths' will find the correct URLs
RUN npm run build

# Default DO port
EXPOSE 8080

# Start command
CMD ["npm", "start", "--", "-p", "8080"]